apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aninetworkpolicy.crd.ani.io
spec:
  group: crd.ani.io
  names:
    kind: ANINetworkPolicy
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description:  This is an application wide network policy.
        properties:
          apiVersion:
            description: A string that identifies the version of ANI schema.
            type: string
          kind:
            description: A string that identifies type of resource.
            type: string
          metadata:
            type: object
          spec:
            description: It is the ANI specific rule specification.
            properties:
              control-policies:
                descriprion: List containing source, destination and rule to be 
                  applied to the connection between them.
                items:
                  action:
                    descriprion: can be 'allow' or 'deny'.
                    type: string
                  source: 
                    descriprion: the source for this particular protocol.
                    properties:
                      cluster:
                        items:
                          type: string
                        type: array
                      node: 
                        items:
                          type: string
                        type: array
                      namespace:
                        items:
                          type: string
                        type: array
                      name: 
                        items:
                          type: string
                        type: array    
                      ip: 
                        items:
                          type: string
                        type: array
                      ports:
                        items:
                          type: string
                        type: array
                      labels:
                        items:
                          type: string
                        type: array
                    type: object
                  destination:
                    descriprion: the destination for this particular protocol.
                    properties:
                      cluster:
                        items:
                          type: string
                        type: array
                      node: 
                        items:
                          type: string
                        type: array
                      namespace:
                        items:
                          type: string
                        type: array
                      name: 
                        items:
                          type: string
                        type: array     
                      ip: 
                        items:
                          type: string
                        type: array
                      ports:
                        items:
                          type: string
                        type: array
                      labels:
                        items:
                          type: string
                        type: array
                    type: object
                  order:
                    type: integer
                  bandwidth:
                    type: string
                  http:
                    descriprion: match criteria for http requests.
                    properties: 
                      path:
                        type: string
                      method:
                        type: string
                    type: object
                  rate-limit:
                    descriprion: rate-limit for the current connection
                    properties:
                      units-per-second: 
                        type: string
                    type: object
                  conn-type:
                    type: string
                  port:
                    type: string
                type: array
            type: object